# Определение тональности отзывов на банки с помощью классических алгоритмов машинного обучения

Используем логистическую регрессию и мешок слов.

Чтобы запускать и редактировать код, сохраните копию этого ноутбука себе (Файл -> Создать копию на Диске). Свою копию вы сможете изменять и запускать.

Учебный курс "[Программирование глубоких нейронных сетей на Python](https://openedu.ru/course/urfu/PYDNN/)".

<a target="_blank" href="https://colab.research.google.com/github/sozykin/dlpython_course/blob/master/text_processing/text_classification.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [ ]:
pip install pymorphy3[fast]

Requirement already satisfied: pymorphy3 in c:\users\sozyk\projects\dlpython_course\.venv\lib\site-packages (2.0.6)
Requirement already satisfied: dawg2-python>=0.8.0 in c:\users\sozyk\projects\dlpython_course\.venv\lib\site-packages (from pymorphy3) (0.9.0)
Requirement already satisfied: pymorphy3-dicts-ru in c:\users\sozyk\projects\dlpython_course\.venv\lib\site-packages (from pymorphy3) (2.4.417150.4580142)
Requirement already satisfied: setuptools>=68.2.2 in c:\users\sozyk\projects\dlpython_course\.venv\lib\site-packages (from pymorphy3) (80.9.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
import numpy as np
import pymorphy3
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from collections import Counter
from pathlib import Path

In [7]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sozyk\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\sozyk\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sozyk\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

Константы

In [8]:
max_words = 10000
random_state = 42

## Загружаем и готовим набор данных

In [9]:
data_path = 'data'

In [10]:
path = Path(data_path)

if not path.exists():
    path.mkdir(parents=True, exist_ok=True)

In [11]:
!curl -s -L -o data/banks.csv "https://www.dropbox.com/scl/fi/mhiwx4plaua183bnuqt5e/train2.csv?rlkey=wv4dalbsutmzu5br9qv5ez21v&dl=1"

In [13]:
banks = pd.read_csv('data/banks.csv', index_col='id');

In [14]:
banks

                                                    text  label
id
0      В Альфа-Банке работает замечательная девушка -...      1
1      Оформляя рассрочку в м. Видео в меге тёплый ст...      0
2      Очень порадовала оперативность работы в банке....      1
3      Имела неосторожность оформить потреб. кредит в...      0
4      Небольшая предыстория: Нашел на сайте MDM банк...      0
...                                                  ...    ...
13994  О высокой надёжности МКБ, порядочности и добро...      1
13995  Обслуживаюсь в офисе на Чернореченской 42а, ка...      1
13996  Попала сегодня в очень неприятную ситуацию. Ре...      1
13997  Добрый день! Давно являюсь клиентом банка Русс...      1
13998  Сначала было все банально. Взял в кредит mp3 п...      0

[13999 rows x 2 columns]

In [15]:
def preprocess(text, stop_words, punctuation_marks, morph):
    tokens = word_tokenize(text.lower())
    preprocessed_text = []
    for token in tokens:
        if token not in punctuation_marks:
            lemma = morph.parse(token)[0].normal_form
            if lemma not in stop_words:
                preprocessed_text.append(lemma)
    return preprocessed_text

In [16]:
punctuation_marks = ['!', ',', '(', ')', ':', '-', '?', '.', '..', '...', '«', '»', ';', '–', '--']
stop_words = stopwords.words("russian")
morph = pymorphy3.MorphAnalyzer()

In [17]:
banks['Preprocessed_texts'] = banks.apply(lambda row: preprocess(row['text'], stop_words, punctuation_marks, morph), axis=1)

In [18]:
banks

,text,label,Preprocessed_texts
id,,,
0,В Альфа-Банке работает замечательная девушка -...,1,"[альфа-банк, работать, замечательный, девушка,..."
1,Оформляя рассрочку в м. Видео в меге тёплый ст...,0,"[оформлять, рассрочка, м., видео, мег, тёплый,..."
2,Очень порадовала оперативность работы в банке....,1,"[очень, порадовать, оперативность, работа, бан..."
3,Имела неосторожность оформить потреб. кредит в...,0,"[иметь, неосторожность, оформить, потреба, кре..."
4,Небольшая предыстория: Нашел на сайте MDM банк...,0,"[небольшой, предыстория, найти, сайт, mdm, бан..."
...,...,...,...
13994,"О высокой надёжности МКБ, порядочности и добро...",1,"[высокий, надёжность, мкб, порядочность, добро..."
13995,"Обслуживаюсь в офисе на Чернореченской 42а, ка...",1,"[обслуживаться, офис, чернореченский, 42а, физ..."
13996,Попала сегодня в очень неприятную ситуацию. Ре...,1,"[попасть, сегодня, очень, неприятный, ситуация..."
13997,Добрый день! Давно являюсь клиентом банка Русс...,1,"[добрый, день, давно, являться, клиент, банк, ..."
13998,Сначала было все банально. Взял в кредит mp3 п...,0,"[сначала, всё, банально, взять, кредит, mp3, п..."

Считаем частоту слов во всех отзывах

In [19]:
words = Counter()

In [20]:
for txt in banks['Preprocessed_texts']:
    words.update(txt)

In [21]:
words.most_common(20)

[('банк', 58189),
 ('карта', 30560),
 ('это', 28660),
 ('всё', 20599),
 ('день', 15729),
 ('сотрудник', 14527),
 ('который', 14519),
 ('кредит', 14490),
 ('деньга', 13701),
 ('счёт', 13681),
 ('отделение', 13414),
 ('клиент', 12681),
 ('мочь', 11140),
 ('свой', 11128),
 ('год', 10378),
 ('сказать', 9990),
 ('вопрос', 9638),
 ('ещё', 9606),
 ('очень', 9226),
 ('весь', 9004)]

Создаем словарь, упорядоченный по частоте

В словаре будем использовать 2 специальных кода:
- Код заполнитель: 0
- Неизвестное слово: 1

Нумерация слов в словаре начинается с 2.

In [22]:
# Словарь, отображающий слова в коды
word_to_index = dict()
# Словарь, отображающий коды в слова
index_to_word = dict()

Создаем словари

In [23]:
for i, word in enumerate(words.most_common(max_words - 2)):
    word_to_index[word[0]] = i + 2
    index_to_word[i + 2] = word[0]

In [24]:
word_to_index

{'банк': 2,
 'карта': 3,
 'это': 4,
 'всё': 5,
 'день': 6,
 'сотрудник': 7,
 'который': 8,
 'кредит': 9,
 'деньга': 10,
 'счёт': 11,
 'отделение': 12,
 'клиент': 13,
 'мочь': 14,
 'свой': 15,
 'год': 16,
 'сказать': 17,
 'вопрос': 18,
 'ещё': 19,
 'очень': 20,
 'весь': 21,
 'время': 22,
 'сумма': 23,
 'кредитный': 24,
 'получить': 25,
 'офис': 26,
 'проблема': 27,
 'заявление': 28,
 'договор': 29,
 'работа': 30,
 'платёж': 31,
 'банкомат': 32,
 'телефон': 33,
 'позвонить': 34,
 'месяц': 35,
 'документ': 36,
 'дать': 37,
 'ответ': 38,
 'решить': 39,
 'хотеть': 40,
 'обслуживание': 41,
 'звонить': 42,
 'ваш': 43,
 'работать': 44,
 'услуга': 45,
 'претензия': 46,
 'прийти': 47,
 'вклад': 48,
 'звонок': 49,
 'номер': 50,
 'написать': 51,
 'большой': 52,
 'ситуация': 53,
 'рубль': 54,
 'человек': 55,
 'минута': 56,
 'сделать': 57,
 'просто': 58,
 'говорить': 59,
 'средство': 60,
 'альфа-банк': 61,
 'заявка': 62,
 'срок': 63,
 'очередь': 64,
 '2': 65,
 'первый': 66,
 'знать': 67,
 'информация': 68,
 'новый': 69,
 'оформить': 70,
 'должный': 71,
 'обратиться': 72,
 'спасибо': 73,
 'смс': 74,
 'пользоваться': 75,
 'девушка': 76,
 'данный': 77,
 'комиссия': 78,
 'никакой': 79,
 'несколько': 80,
 '%': 81,
 'менеджер': 82,
 'процент': 83,
 'являться': 84,
 'сайт': 85,
 'операция': 86,
 'условие': 87,
 'хороший': 88,
 'оператор': 89,
 'отзыв': 90,
 'стать': 91,
 'решение': 92,
 'нужно': 93,
 'сообщить': 94,
 'ждать': 95,
 'сразу': 96,
 'специалист': 97,
 'также': 98,
 'почему': 99,
 'неделя': 100,
 'перевод': 101,
 'течение': 102,
 'час': 103,
 'сегодня': 104,
 'ответить': 105,
 'хотя': 106,
 'т.к': 107,
 'момент': 108,
 'писать': 109,
 'следующий': 110,
 '*': 111,
 'обращение': 112,
 'иметь': 113,
 '5': 114,
 'открыть': 115,
 'просить': 116,
 '3': 117,
 '10': 118,
 'отношение': 119,
 'г.': 120,
 'взять': 121,
 'быстро': 122,
 'случай': 123,
 'предложить': 124,
 'линия': 125,
 'наш': 126,
 'задолженность': 127,
 'итог': 128,
 'выдать': 129,
 'самый': 130,
 'вообще': 131,
 'делать': 132,
 'общий': 133,
 'дело': 134,
 'принять': 135,
 'сбербанк': 136,
 'лимит': 137,
 'оказаться': 138,
 'каждый': 139,
 'смочь': 140,
 'руб': 141,
 'оплата': 142,
 'нужный': 143,
 'пройти': 144,
 'пока': 145,
 'приходить': 146,
 'страховка': 147,
 'объяснить': 148,
 'думать': 149,
 'слово': 150,
 'какой-то': 151,
 'получение': 152,
 'помочь': 153,
 'никто': 154,
 'прийтись': 155,
 'горячий': 156,
 'погашение': 157,
 'альфа': 158,
 'оформление': 159,
 'вернуть': 160,
 'история': 161,
 'брать': 162,
 'попросить': 163,
 'именно': 164,
 'последний': 165,
 '1': 166,
 'возможность': 167,
 'сотрудница': 168,
 'адрес': 169,
 'закрыть': 170,
 'получать': 171,
 'узнать': 172,
 'добрый': 173,
 'служба': 174,
 'интернет': 175,
 'внести': 176,
 'ошибка': 177,
 'идти': 178,
 'друг': 179,
 'система': 180,
 'хотеться': 181,
 'указать': 182,
 'оплатить': 183,
 'снова': 184,
 'любой': 185,
 'рабочий': 186,
 'москва': 187,
 'денежный': 188,
 'покупка': 189,
 'около': 190,
 'лицо': 191,
 'платить': 192,
 'положительный': 193,
 'вежливый': 194,
 'отправить': 195,
 'снять': 196,
 'оставить': 197,
 'поэтому': 198,
 'видеть': 199,
 'назад': 200,
 'касса': 201,
 'связь': 202,
 'конец': 203,
 'поддержка': 204,
 'дебетовый': 205,
 '000': 206,
 'остаться': 207,
 'справка': 208,
 'предоставить': 209,
 'отвечать': 210,
 'банковский': 211,
 'второй': 212,
 'погасить': 213,
 'место': 214,
 'карточка': 215,
 'письмо': 216,
 'обращаться': 217,
 'полный': 218,
 'понимать': 219,
 'просьба': 220,
 'долг': 221,
 'рассмотрение': 222,
 'закрытие': 223,
 'причина': 224,
 'ставка': 225,
 'открытие': 226,
 'что-то': 227,
 'приехать': 228,
 'продукт': 229,
 'дата': 230,
 'находиться': 231,
 'бинбанка': 232,
 'страхование': 233,
 'отказ': 234,
 'приятно': 235,
 'сторона': 236,
 'давать': 237,
 'личный': 238,
 'уточнить': 239,
 'результат': 240,
 'действие': 241,
 'выписка': 242,
 'паспорт': 243,
 'рассказать': 244,
 'понять': 245,
 'считать': 246,
 '4': 247,
 'из-за': 248,
 'авангард': 249,
 '30': 250,
 'магазин': 251,
 'отдел': 252,
 'тариф': 253,
 'оформлять': 254,
 'кол-центр': 255,
 'число': 256,
 'сделка': 257,
 'списать': 258,
 'далее': 259,
 'дополнительный': 260,
 'отказаться': 261,
 'найти': 262,
 'спросить': 263,
 'пара': 264,
 'разобраться': 265,
 'начать': 266,
 'пытаться': 267,
 'надеяться': 268,
 'одобрить': 269,
 'благодарность': 270,
 'начало': 271,
 'данные': 272,
 'бинбанк': 273,
 'удобный': 274,
 'перезвонить': 275,
 'обещать': 276,
 'готовый': 277,
 'город': 278,
 'программа': 279,
 'предложение': 280,
 'пойти': 281,
 'почта': 282,
 'подать': 283,
 'составить': 284,
 'размер': 285,
 'довольный': 286,
 'внимание': 287,
 'анкета': 288,
 'сервис': 289,
 'пора': 290,
 '15': 291,
 'мобильный': 292,
 'перевести': 293,
 'произойти': 294,
 'имя': 295,
 'общение': 296,
 'необходимый': 297,
 'списание': 298,
 'огромный': 299,
 'помощь': 300,
 'причём': 301,
 '20': 302,
 'поступить': 303,
 'возврат': 304,
 'декабрь': 305,
 'бесплатный': 306,
 'отметить': 307,
 'март': 308,
 'снятие': 309,
 'квартира': 310,
 'долго': 311,
 'её': 312,
 'наличный': 313,
 'стоить': 314,
 'разный': 315,
 'операционист': 316,
 'заполнить': 317,
 'интернет-банк': 318,
 'некоторый': 319,
 'качество': 320,
 'маленький': 321,
 'штраф': 322,
 'рука': 323,
 'очередной': 324,
 'подписать': 325,
 'период': 326,
 'плюс': 327,
 'компания': 328,
 'остаток': 329,
 'зарплатный': 330,
 'филиал': 331,
 'сколько': 332,
 'провести': 333,
 'больший': 334,
 'ул': 335,
 'забрать': 336,
 'представитель': 337,
 'зайти': 338,
 'разговор': 339,
 'просрочка': 340,
 'сообщение': 341,
 'депозит': 342,
 'удобно': 343,
 'действительно': 344,
 'досрочный': 345,
 'связаться': 346,
 'близкий': 347,
 'прислать': 348,
 'обслуживаться': 349,
 'сей': 350,
 'уйти': 351,
 'возникнуть': 352,
 'подключить': 353,
 'увидеть': 354,
 'однако': 355,
 'администратор': 356,
 'т.е': 357,
 'впечатление': 358,
 'приятный': 359,
 'кредитка': 360,
 'порядок': 361,
 'видимо': 362,
 'пакет': 363,
 'дом': 364,
 'заблокировать': 365,
 'право': 366,
 'центр': 367,
 'достаточно': 368,
 'жалоба': 369,
 'выбрать': 370,
 'копия': 371,
 'правда': 372,
 'повод': 373,
 'либо': 374,
 'ожидание': 375,
 'выдача': 376,
 'страховой': 377,
 'работник': 378,
 'электронный': 379,
 'сожаление': 380,
 'необходимо': 381,
 'положить': 382,
 'организация': 383,
 'давно': 384,
 'предлагать': 385,
 'оценка': 386,
 'ранний': 387,
 'высокий': 388,
 'требовать': 389,
 'факт': 390,
 'терминал': 391,
 'тысяча': 392,
 'далёкий': 393,
 'принимать': 394,
 'лично': 395,
 'запрос': 396,
 'апрель': 397,
 'проверить': 398,
 'возможно': 399,
 '7': 400,
 'начаться': 401,
 'текущий': 402,
 'подойти': 403,
 'альф': 404,
 'небольшой': 405,
 'закрытый': 406,
 'жизнь': 407,
 'оплачивать': 408,
 'вид': 409,
 'полностью': 410,
 'минус': 411,
 'суд': 412,
 'спрашивать': 413,
 'точно': 414,
 'кстати': 415,
 'образ': 416,
 'руководитель': 417,
 'кроме': 418,
 'курс': 419,
 'май': 420,
 'январь': 421,
 'общаться': 422,
 'посмотреть': 423,
 'воспользоваться': 424,
 'сначала': 425,
 'отказать': 426,
 'открывать': 427,
 'быстрый': 428,
 'единственный': 429,
 'оперативно': 430,
 'рассмотреть': 431,
 'потребительский': 432,
 'поставить': 433,
 'руководство': 434,
 'опыт': 435,
 'всякий': 436,
 'потратить': 437,
 'требование': 438,
 'ипотека': 439,
 'часть': 440,
 'объяснять': 441,
 'снимать': 442,
 'чек': 443,
 'уровень': 444,
 'ноябрь': 445,
 '6': 446,
 'август': 447,
 'годовой': 448,
 'всё-таки': 449,
 '№': 450,
 'сбер': 451,
 'происходить': 452,
 'сообщать': 453,
 'февраль': 454,
 'купюра': 455,
 'технический': 456,
 'процесс': 457,
 'выразить': 458,
 'понятно': 459,
 'понравиться': 460,
 'заказать': 461,
 'заплатить': 462,
 'отсутствие': 463,
 'ранее': 464,
 'простой': 465,
 'рекомендовать': 466,
 'туда': 467,
 'приходиться': 468,
 'вариант': 469,
 '8': 470,
 'июль': 471,
 'июнь': 472,
 'фамилия': 473,
 'подобный': 474,
 'ежемесячный': 475,
 'знакомый': 476,
 'указанный': 477,
 'занять': 478,
 'забыть': 479,
 'чётко': 480,
 'бывать': 481,
 'форма': 482,
 'появиться': 483,
 'возникать': 484,
 '100': 485,
 'уважаемый': 486,
 'оказываться': 487,
 'попытка': 488,
 'валюта': 489,
 'постоянно': 490,
 'октябрь': 491,
 'подождать': 492,
 'решать': 493,
 'примерно': 494,
 'поздний': 495,
 'вернуться': 496,
 'акция': 497,
 'третий': 498,
 'дозвониться': 499,
 '+': 500,
 'уважение': 501,
 'попасть': 502,
 'телефонный': 503,
 'дальнейший': 504,
 'начислить': 505,
 'желание': 506,
 'назвать': 507,
 'вчера': 508,
 'персонал': 509,
 'здравствуйте': 510,
 'утро': 511,
 'например': 512,
 'вносить': 513,
 'лишь': 514,
 'читать': 515,
 'кабинет': 516,
 'управлять': 517,
 'вроде': 518,
 'получиться': 519,
 'спустя': 520,
 'ожидать': 521,
 'старый': 522,
 'несмотря': 523,
 'жена': 524,
 'цель': 525,
 'как-то': 526,
 'смотреть': 527,
 'рф': 528,
 'естественно': 529,
 'выясниться': 530,
 'выдавать': 531,
 'ипотечный': 532,
 'сидеть': 533,
 'сентябрь': 534,
 'зачислить': 535,
 'честно': 536,
 'интернет-банка': 537,
 'сетель': 538,
 'поступать': 539,
 'расчётный': 540,
 'получаться': 541,
 'подтвердить': 542,
 '2016': 543,
 'выяснить': 544,
 'поскольку': 545,
 'ехать': 546,
 'передать': 547,
 'мало': 548,
 'молодой': 549,
 'трубка': 550,
 'выйти': 551,
 'перевыпуск': 552,
 'главное': 553,
 'россия': 554,
 'выпустить': 555,
 'плохой': 556,
 'немного': 557,
 'подумать': 558,
 'менее': 559,
 'помнить': 560,
 'оставаться': 561,
 'наверное': 562,
 'проходить': 563,
 'кассир': 564,
 'ладный': 565,
 'начинать': 566,
 'заниматься': 567,
 'отдельный': 568,
 'кто-то': 569,
 'равно': 570,
 'вместо': 571,
 'сотрудничество': 572,
 'пожалуйста': 573,
 'активировать': 574,
 'нравиться': 575,
 'процедура': 576,
 'консультант': 577,
 'ставить': 578,
 'машина': 579,
 'основание': 580,
 'вечером': 581,
 'кредитование': 582,
 'бонус': 583,
 'согласиться': 584,
 'онлайн': 585,
 'евро': 586,
 'зарплата': 587,
 'выбор': 588,
 'отличный': 589,
 'выпуск': 590,
 'внесение': 591,
 'сутки': 592,
 'досрочно': 593,
 'пункт': 594,
 'потерять': 595,
 'поехать': 596,
 'необходимость': 597,
 'обнаружить': 598,
 'крупный': 599,
 'реквизит': 600,
 'закончиться': 601,
 'доллар': 602,
 'бумага': 603,
 'целое': 604,
 'посоветовать': 605,
 'составлять': 606,
 'особенно': 607,
 'сбой': 608,
 'обслуживать': 609,
 'стоять': 610,
 'собираться': 611,
 'обычно': 612,
 'visa': 613,
 'подпись': 614,
 'недавно': 615,
 'московский': 616,
 'персональный': 617,
 'тыс': 618,
 'уведомление': 619,
 '2014': 620,
 'иметься': 621,
 'практически': 622,
 'консультация': 623,
 'остальной': 624,
 'пополнение': 625,
 'минимальный': 626,
 'завтра': 627,
 'затем': 628,
 'собственный': 629,
 'количество': 630,
 'бесплатно': 631,
 'купить': 632,
 'интересный': 633,
 'база': 634,
 'муж': 635,
 'наличие': 636,
 'ткс': 637,
 'срочно': 638,
 'правило': 639,
 'использовать': 640,
 'безопасность': 641,
 'закон': 642,
 'финансовый': 643,
 'искать': 644,
 'заранее': 645,
 'изменение': 646,
 'успеть': 647,
 'отрицательный': 648,
 'действовать': 649,
 'часто': 650,
 'льготный': 651,
 'лишний': 652,
 'процентный': 653,
 'р.': 654,
 'казаться': 655,
 'подробно': 656,
 'мера': 657,
 'жить': 658,
 'русский': 659,
 'выходной': 660,
 'заметить': 661,
 'товар': 662,
 'одобрение': 663,
 'довольно': 664,
 'пять': 665,
 'невозможно': 666,
 'удивить': 667,
 'предыдущий': 668,
 'т.д': 669,
 'сложиться': 670,
 'вечер': 671,
 'подавать': 672,
 'удаться': 673,
 'профессионализм': 674,
 'возможный': 675,
 'стандарт': 676,
 '9': 677,
 'вовремя': 678,
 'отключить': 679,
 'оставлять': 680,
 'пример': 681,
 'отдать': 682,
 'предоставление': 683,
 'пользование': 684,
 'код': 685,
 'нормальный': 686,
 'выплата': 687,
 'транзакция': 688,
 'соответственно': 689,
 'совершить': 690,
 'выгодный': 691,
 'подтверждение': 692,
 'письменный': 693,
 '12': 694,
 'совершенно': 695,
 'план': 696,
 'устраивать': 697,
 'разбираться': 698,
 'руб.': 699,
 'проспект': 700,
 'использование': 701,
 '2015': 702,
 'мол': 703,
 'крайне': 704,
 'домой': 705,
 'ввести': 706,
 'стоимость': 707,
 'доход': 708,
 'зачисление': 709,
 'подходить': 710,
 'посещение': 711,
 'закрывать': 712,
 'какой-либо': 713,
 'автокредит': 714,
 '50': 715,
 'мнение': 716,
 'удивление': 717,
 'встреча': 718,
 'благодаря': 719,
 'желать': 720,
 'продолжать': 721,
 'выше': 722,
 'тратить': 723,
 'прошлый': 724,
 'понедельник': 725,
 'визит': 726,
 'долгий': 727,
 'перевыпустить': 728,
 'админ': 729,
 'проводить': 730,
 'проверка': 731,
 'заверить': 732,
 'просрочить': 733,
 'рядом': 734,
 'платёжный': 735,
 'график': 736,
 'согласно': 737,
 'тип': 738,
 'пароль': 739,
 'якобы': 740,
 'никак': 741,
 'случиться': 742,
 'заявить': 743,
 '21': 744,
 'операционистка': 745,
 'согласие': 746,
 'приложение': 747,
 'услышать': 748,
 'ребёнок': 749,
 'наличные': 750,
 'абсолютно': 751,
 'зарегистрировать': 752,
 '40': 753,
 'принцип': 754,
 'задать': 755,
 'предупредить': 756,
 'направить': 757,
 'начисление': 758,
 'переводить': 759,
 'обычный': 760,
 'поблагодарить': 761,
 'привести': 762,
 'нормально': 763,
 'попробовать': 764,
 'вполне': 765,
 'выполнить': 766,
 'баланс': 767,
 'подписывать': 768,
 '25': 769,
 'полгода': 770,
 'валютный': 771,
 'держать': 772,
 'настоящий': 773,
 'ходить': 774,
 'обязательно': 775,
 'доступ': 776,
 '2013': 777,
 '11': 778,
 'где-то': 779,
 'состояние': 780,
 'взнос': 781,
 'внимательный': 782,
 'вместе': 783,
 'спокойно': 784,
 'коллега': 785,
 'многий': 786,
 'произвести': 787,
 'вынудить': 788,
 'регистрация': 789,
 'буквально': 790,
 '14': 791,
 'мкб': 792,
 'подача': 793,
 'предоставлять': 794,
 'описать': 795,
 'расчёт': 796,
 'пояснить': 797,
 'контактный': 798,
 'слышать': 799,
 'пополнить': 800,
 'доп': 801,
 'список': 802,
 'точка': 803,
 'исправить': 804,
 'ооо': 805,
 'понадобиться': 806,
 'отказываться': 807,
 'негативный': 808,
 'прочитать': 809,
 'обратно': 810,
 'заходить': 811,
 'отправлять': 812,
 'конкретный': 813,
 'решаться': 814,
 'извинение': 815,
 'обязательство': 816,
 'мама': 817,
 'суббота': 818,
 '500': 819,
 'елена': 820,
 'постоянный': 821,
 'мдм': 822,
 'значит': 823,
 'полис': 824,
 'плата': 825,
 'кодовый': 826,
 'правильно': 827,
 'иб': 828,
 '18': 829,
 'куча': 830,
 'помогать': 831,
 'принести': 832,
 'вход': 833,
 'способ': 834,
 'вывод': 835,
 'рассрочка': 836,
 'распечатать': 837,
 'минимум': 838,
 'оба': 839,
 'нерв': 840,
 'подписание': 841,
 'утром': 842,
 'платный': 843,
 'почему-то': 844,
 'компьютер': 845,
 'профессиональный': 846,
 'мелочь': 847,
 'ольга': 848,
 'попытаться': 849,
 'рассматривать': 850,
 'приезжать': 851,
 'разговаривать': 852,
 'граница': 853,
 'столкнуться': 854,
 'прямо': 855,
 'показать': 856,
 'проверять': 857,
 'мина': 858,
 'окончание': 859,
 'сильно': 860,
 'узнавать': 861,
 'уточнять': 862,
 'официальный': 863,
 'центральный': 864,
 'оно': 865,
 'относиться': 866,
 'реклама': 867,
 'вновь': 868,
 'супруг': 869,
 'грамотный': 870,
 'послать': 871,
 'компетентный': 872,
 'обратить': 873,
 'альфа-клик': 874,
 'собственно': 875,
 'пятница': 876,
 'вина': 877,
 'заполнять': 878,
 'называть': 879,
 'объяснение': 880,
 'планировать': 881,
 'удивлённый': 882,
 'успешно': 883,
 'александр': 884,
 'понимание': 885,
 'учёт': 886,
 'страна': 887,
 'пусть': 888,
 '24': 889,
 'оперативность': 890,
 'соответствовать': 891,
 'екатерина': 892,
 'оперативный': 893,
 'отпуск': 894,
 'поменять': 895,
 'замечательный': 896,
 '—': 897,
 'иной': 898,
 'смена': 899,
 '3-й': 900,
 'заёмщик': 901,
 'советовать': 902,
 'наталья': 903,
 'изменить': 904,
 'повторно': 905,
 'абсолют': 906,
 'качественный': 907,
 'радовать': 908,
 'приём': 909,
 'глаз': 910,
 'менять': 911,
 '45': 912,
 'вкладчик': 913,
 'юридический': 914,
 'девочка': 915,
 'улица': 916,
 'подход': 917,
 'подтверждать': 918,
 'метро': 919,
 'скорее': 920,
 '2-й': 921,
 'сила': 922,
 'подробный': 923,
 'откуда': 924,
 'интересовать': 925,
 'птс': 926,
 'квитанция': 927,
 'уходить': 928,
 'ирина': 929,
 'определённый': 930,
 'доброжелательный': 931,
 'покупать': 932,
 'неоднократно': 933,
 'семья': 934,
 'совет': 935,
 'таки': 936,
 'многие': 937,
 'хватать': 938,
 'копейка': 939,
 'зал': 940,
 'call-центр': 941,
 'автомобиль': 942,
 'юлия': 943,
 'назначить': 944,
 'полчаса': 945,
 'санкт-петербург': 946,
 'ситибанк': 947,
 'рублёвый': 948,
 'хоум': 949,
 'подарок': 950,
 'татьяна': 951,
 'низкий': 952,
 'встречать': 953,
 'заказывать': 954,
 'доступный': 955,
 '16': 956,
 'продавец': 957,
 'видно': 958,
 'сталкиваться': 959,
 'клиентский': 960,
 'взыскание': 961,
 'требоваться': 962,
 'некий': 963,
 'подключение': 964,
 'статус': 965,
 'оао': 966,
 'рейтинг': 967,
 'проект': 968,
 'билет': 969,
 'важный': 970,
 'неприятный': 971,
 'отменить': 972,
 'перечислить': 973,
 'надежда': 974,
 'смысл': 975,
 'пригласить': 976,
 'увеличить': 977,
 'поделиться': 978,
 '....': 979,
 'народ': 980,
 'защита': 981,
 'дождаться': 982,
 'цб': 983,
 'иначе': 984,
 'везде': 985,
 'установить': 986,
 'отлично': 987,
 'вести': 988,
 'интересно': 989,
 'приветливый': 990,
 'каско': 991,
 'поездка': 992,
 'пополнять': 993,
 'голос': 994,
 '13': 995,
 'задавать': 996,
 'сравнение': 997,
 'индивидуальный': 998,
 'пообещать': 999,
 'заключить': 1000,
 'внутренний': 1001,
 ...}

Функция для преобразования списка слов в список кодов

In [25]:
def text_to_sequence(txt, word_to_index):
    seq = []
    for word in txt:
        index = word_to_index.get(word, 1) # 1 означает неизвестное слово
        # Неизвестные слова не добавляем в выходную последовательность
        if index != 1:
            seq.append(index)
    return seq

Преобразуем все тексты в последовательность кодов слов

In [26]:
banks['Sequences'] = banks.apply(lambda row: text_to_sequence(row['Preprocessed_texts'], word_to_index), axis=1)

In [27]:
banks

,text,label,Preprocessed_texts,Sequences
id,,,,
0,В Альфа-Банке работает замечательная девушка -...,1,"[альфа-банк, работать, замечательный, девушка,...","[61, 44, 896, 76, 194, 1842, 344, 2685, 396, 1..."
1,Оформляя рассрочку в м. Видео в меге тёплый ст...,0,"[оформлять, рассрочка, м., видео, мег, тёплый,...","[254, 836, 1155, 3189, 3865, 2956, 7316, 163, ..."
2,Очень порадовала оперативность работы в банке....,1,"[очень, порадовать, оперативность, работа, бан...","[20, 1033, 890, 30, 2, 461, 175, 3, 613, 1743,..."
3,Имела неосторожность оформить потреб. кредит в...,0,"[иметь, неосторожность, оформить, потреба, кре...","[113, 4790, 70, 2343, 9, 61, 20, 2639, 1264, 3..."
4,Небольшая предыстория: Нашел на сайте MDM банк...,0,"[небольшой, предыстория, найти, сайт, mdm, бан...","[405, 3824, 262, 85, 2, 633, 3, 4866, 2, 283, ..."
...,...,...,...,...
13994,"О высокой надёжности МКБ, порядочности и добро...",1,"[высокий, надёжность, мкб, порядочность, добро...","[388, 2296, 792, 5000, 8128, 7, 3073, 120, 427..."
13995,"Обслуживаюсь в офисе на Чернореченской 42а, ка...",1,"[обслуживаться, офис, чернореченский, 42а, физ...","[349, 26, 9465, 2126, 191, 16, 26, 134, 64, 11..."
13996,Попала сегодня в очень неприятную ситуацию. Ре...,1,"[попасть, сегодня, очень, неприятный, ситуация...","[502, 104, 20, 971, 53, 39, 213, 221, 3, 47, 3..."
13997,Добрый день! Давно являюсь клиентом банка Русс...,1,"[добрый, день, давно, являться, клиент, банк, ...","[173, 6, 384, 84, 13, 2, 659, 676, 113, 330, 3..."
13998,Сначала было все банально. Взял в кредит mp3 п...,0,"[сначала, всё, банально, взять, кредит, mp3, п...","[425, 5, 4084, 121, 9, 446, 2012, 192, 645, 39..."

## Готовим данные для обучения

### Выделяем данные для обучения и тестирования

In [28]:
train, test = train_test_split(banks, test_size=0.2)

In [29]:
train

,text,label,Preprocessed_texts,Sequences
id,,,,
10648,Около месяца назад на мой мобильный телефон ст...,0,"[около, месяц, назад, мобильный, телефон, стат...","[190, 35, 200, 292, 33, 91, 146, 341, 2, 249, ..."
2922,У меня имеется открытый вклад Великолепная сем...,0,"[иметься, открытый, вклад, великолепный, семёр...","[621, 1028, 48, 2561, 7301, 1043, 171, 60, 579..."
8955,"Итак, в итоге решил я перейти из Райфайзена в ...",1,"[итак, итог, решить, перейти, райфайзть, аванг...","[1537, 128, 39, 1321, 249, 1642, 249, 792, 166..."
10410,В сентябре был открыт валютный счет-копилка в ...,0,"[сентябрь, открыть, валютный, счёт-копилка, эт...","[534, 115, 771, 4, 2, 806, 2215, 60, 7903, 494..."
11095,Давно являюсь клиентом Банка и это давно не су...,1,"[давно, являться, клиент, банк, это, давно, су...","[384, 84, 13, 2, 4, 384, 1197, 4, 2, 2399, 210..."
...,...,...,...,...
4172,Добрый день!Хотел бы поблагодарить отдел прете...,1,"[добрый, день, хотеть, поблагодарить, отдел, п...","[173, 6, 40, 761, 252, 1778, 30, 1274, 960, 11..."
11170,Пользуюсь кредиткой Авангарда с 2006 года. Нра...,1,"[пользоваться, кредитка, авангард, 2006, год, ...","[75, 360, 249, 1757, 16, 575, 5, 81, 225, 167,..."
8446,Имел возможность сравнить качество обслуживани...,1,"[иметь, возможность, сравнить, качество, обслу...","[113, 167, 1976, 320, 41, 2, 3466, 187, 1741, ..."
12281,ДО ПОХОДНЫЙ ПРОЕЗД.23.12.2015 мы подали докуме...,0,"[походный, проезд.23.12.2015, подать, документ...","[283, 36, 272, 1057, 169, 789, 1108, 102, 900,..."
1300,Уважаемый Бинбанк!Я - бывший клиент банка Евро...,0,"[уважаемый, бинбанк, бывший, клиент, банк, евр...","[486, 273, 1489, 13, 2, 380, 13, 232, 5, 90, 3..."

In [30]:
test

,text,label,Preprocessed_texts,Sequences
id,,,,
13777,У меня оформлен автокредит в Сетелем Банке - п...,1,"[оформить, автокредит, сетель, банк, причина, ...","[70, 714, 538, 2, 224, 588, 77, 211, 2059, 465..."
10115,Давно не пользовался услугами Сбербанка. Очень...,1,"[давно, пользоваться, услуга, сбербанк, очень,...","[384, 75, 45, 136, 20, 384, 1738, 351, 159, 14..."
10842,"Я - несчастный бывший клиент Пробизнесбанка, п...",0,"[несчастный, бывший, клиент, пробизнесбанк, пр...","[3004, 1489, 13, 8670, 7424, 8, 91, 273, 48, 4..."
8090,История такая! Прорекламировали мне карту Плат...,0,"[история, прорекламировать, карта, платиновый,...","[161, 3, 2117, 3, 2141, 20, 3344, 311, 423, 25..."
9749,По инициативе банка были заблокированы 2 карты...,0,"[инициатива, банк, заблокировать, 2, карта, де...","[2075, 2, 365, 65, 3, 205, 24, 1962, 880, 224,..."
...,...,...,...,...
13852,Добрый день! Обычно люди склонны жаловаться на...,1,"[добрый, день, обычно, человек, склонный, жало...","[173, 6, 612, 55, 1733, 556, 3209, 88, 164, 19..."
1176,"Брал кредит, всё нормально выплатил, единствен...",1,"[брать, кредит, всё, нормально, выплатить, еди...","[162, 9, 5, 763, 1085, 429, 1845, 24, 3, 463, ..."
7148,Несколько лет назад мы с дочерью делали ремонт...,1,"[несколько, год, назад, дочь, делать, ремонт, ...","[80, 16, 200, 2304, 132, 1657, 310, 39, 895, 5..."
895,Выражаю свою признательность и огромную благод...,1,"[выражать, свой, признательность, огромный, бл...","[1179, 15, 2544, 299, 270, 7, 136, 554, 5818, ..."
3434,Искренни благодарю сотрудника Альфа-Банка за к...,1,"[искренний, благодарить, сотрудник, альфа-банк...","[1702, 1212, 7, 61, 907, 872, 300, 2605, 122, ..."

### Разделяем метки классов и данные для обучения

Данные для обучения

In [31]:
x_train_seq = train['Sequences']
y_train = train['label']

In [32]:
x_train_seq

id
10648    [190, 35, 200, 292, 33, 91, 146, 341, 2, 249, ...
2922     [621, 1028, 48, 2561, 7301, 1043, 171, 60, 579...
8955     [1537, 128, 39, 1321, 249, 1642, 249, 792, 166...
10410    [534, 115, 771, 4, 2, 806, 2215, 60, 7903, 494...
11095    [384, 84, 13, 2, 4, 384, 1197, 4, 2, 2399, 210...
                               ...
4172     [173, 6, 40, 761, 252, 1778, 30, 1274, 960, 11...
11170    [75, 360, 249, 1757, 16, 575, 5, 81, 225, 167,...
8446     [113, 167, 1976, 320, 41, 2, 3466, 187, 1741, ...
12281    [283, 36, 272, 1057, 169, 789, 1108, 102, 900,...
1300     [486, 273, 1489, 13, 2, 380, 13, 232, 5, 90, 3...
Name: Sequences, Length: 11199, dtype: object

In [33]:
y_train

id
10648    0
2922     0
8955     1
10410    0
11095    1
        ..
4172     1
11170    1
8446     1
12281    0
1300     0
Name: label, Length: 11199, dtype: int64

Данные для тестирования

In [34]:
x_test_seq = test['Sequences']
y_test = test['label']

In [35]:
x_test_seq

id
13777    [70, 714, 538, 2, 224, 588, 77, 211, 2059, 465...
10115    [384, 75, 45, 136, 20, 384, 1738, 351, 159, 14...
10842    [3004, 1489, 13, 8670, 7424, 8, 91, 273, 48, 4...
8090     [161, 3, 2117, 3, 2141, 20, 3344, 311, 423, 25...
9749     [2075, 2, 365, 65, 3, 205, 24, 1962, 880, 224,...
                               ...
13852    [173, 6, 612, 55, 1733, 556, 3209, 88, 164, 19...
1176     [162, 9, 5, 763, 1085, 429, 1845, 24, 3, 463, ...
7148     [80, 16, 200, 2304, 132, 1657, 310, 39, 895, 5...
895      [1179, 15, 2544, 299, 270, 7, 136, 554, 5818, ...
3434     [1702, 1212, 7, 61, 907, 872, 300, 2605, 122, ...
Name: Sequences, Length: 2800, dtype: object

In [36]:
y_test

id
13777    1
10115    1
10842    0
8090     0
9749     0
        ..
13852    1
1176     1
7148     1
895      1
3434     1
Name: label, Length: 2800, dtype: int64

## Создаем мешок слов

In [37]:
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        for index in sequence:
            results[i, index] += 1.
    return results

In [38]:
x_train = vectorize_sequences(x_train_seq, max_words)

In [39]:
x_test = vectorize_sequences(x_test_seq, max_words)

In [40]:
x_train[0][:100]

array([0., 0., 4., 0., 2., 0., 1., 1., 2., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 3.,
       0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 0., 1., 0., 0., 0., 0., 3.,
       0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
len(x_train[0])

10000

## Создаем модель машинного обучения

In [42]:
lr = LogisticRegression(random_state=random_state, max_iter=500)

## Обучаем модель машинного обучения

In [43]:
lr.fit(x_train, y_train)

LogisticRegression(max_iter=500, random_state=42)

## Оцениваем качество обучения на тестовом наборе данных

Определяем долю правильных ответов (accuracy) на тестовом наборе данных

In [44]:
lr.score(x_test, y_test)

0.9414285714285714

## Применяем модель для определения тональности отзыва на банк

**Позитивный отзыв**

In [45]:
positive_text = """Брал кредит в Мегабанке на автомобиль. Выдали за один день. Никаких скрытых комиссий и переплат.
У банка удобное мобильное приложение, через которое можно быстро отправить ежемесячный платеж.
Досрочное гасить начал через три месяца. Я доволен оперативностью и удобством. Огромное спасибо!
"""

Подготовка текста к обработке

In [46]:
positive_preprocessed_text = preprocess(positive_text, stop_words, punctuation_marks, morph)

In [47]:
positive_preprocessed_text

['брать',
 'кредит',
 'мегабанк',
 'автомобиль',
 'выдать',
 'день',
 'никакой',
 'скрытый',
 'комиссия',
 'переплата',
 'банк',
 'удобный',
 'мобильный',
 'приложение',
 'который',
 'быстро',
 'отправить',
 'ежемесячный',
 'платёж',
 'досрочный',
 'гасить',
 'начать',
 'месяц',
 'довольный',
 'оперативность',
 'удобство',
 'огромный',
 'спасибо']

In [48]:
positive_seq = text_to_sequence(positive_preprocessed_text, word_to_index)

In [49]:
positive_seq

[162,
 9,
 942,
 129,
 6,
 79,
 1866,
 78,
 1007,
 2,
 274,
 292,
 747,
 8,
 122,
 195,
 475,
 31,
 345,
 1399,
 266,
 35,
 286,
 890,
 1293,
 299,
 73]

In [50]:
positive_bow = vectorize_sequences([positive_seq], max_words)

In [51]:
positive_bow[0][0:100]

array([0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Выполняем распознавание

In [52]:
result = lr.predict(positive_bow)

In [53]:
result

array([1])

**Негативный отзыв**

In [54]:
negative_text = """Взял кредит в ТакСебеБанке на автомобиль. В договор включили обязательный контракт
на помощь на дороге, который мне не нужен. Узнал об этом только во время подписания договора, иначе бы отказался.
Альтернативы была страхование жизни, но мне это даже не предложили. Скорее всего, менеджер продвигает
продажи услуг этой компании в ущерб интересов клиента. Как минимум, непорядочно и непрофессионально.
У банка ужасное мобильное приложение, из-за которого с меня взяли штраф 10 тыс.руб. По требованиям
банка после покупки автомобиля в приложении нужно загрузить ПТС. Я загрузил и проверил, что ПТС в приложении есть.
Но через некоторое время ПТС из приложения пропал и с меня взяли штраф. Никому не рекомендую связываться с ТакСебеБанком.
"""

In [55]:
negative_preprocessed_text = preprocess(negative_text, stop_words, punctuation_marks, morph)
negative_seq = text_to_sequence(negative_preprocessed_text, word_to_index)
negative_bow = vectorize_sequences([negative_seq], max_words)

In [56]:
negative_bow[0][0:100]

array([0., 0., 2., 0., 2., 0., 0., 0., 2., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 2., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [57]:
result = lr.predict(negative_bow)

In [58]:
result

array([0])

In [59]:
result = lr.predict_proba(negative_bow)

In [60]:
result

array([[0.99678078, 0.00321922]])